language: node_js
node_js:
- '5'
before_install:
- npm install -g gulp
script: gulp test
addons:
  sauce_connect:
    username: trbustamante
env:
  global:
    secure: nJohqDpEYSbXlE/jFaPzsymtO1kKpWgQE0Hq7uvcIKX9jN9++9LFUWAXnfPZE6hDEaBp9YgqR3sPlSg0KgPTNhuMv0UMddEtADBALPUagP/honSbzsIqP8Yi8bOBVwKA6uIiU0OBbNE+8CrVWCO+8PQHu3N9SAofjUPJtdLIAoNDNbO036BL4oxw5vWQYIZoGLrT1e66TsndfNYqnO4e/2bmhnyxj1Zp9lYvtswkTKFDEsOhWB6jXtqIN3bI9HfXUmQTv0SrA3dXviK/IhIKTpMXGnAeXV/hEClYmWonAyCFwp8EAlLqvYIFgPBo3eMrD4/E3V659yNw7Ulxa2q7cJBpq6SjIhhgdBRCPmMdsMWOZ6B4DI0v1D1iIIIaVzpyv4th+RELrhsLtypYFquAuvjMu6sv9GRvO8MHBwRJit7zEpwt9Gde0a/VvKXkba8XbBngV0pwkaCmyaT27gg8WXIYFzXtZaTJcycZ5M83yN3KB9HedjXyrbmlSYlM7UPUAF5yFki76ybJYnE07Gb+z5EIasd2ZTX7FTYHQzltzFmTfpKwAQmLgeSJ24hK0qsDhmpTujdT6PrfdKcdWqQq950qCCF8jWxdTur6WKVf/m/5vLwAfr9Vcd+tsdfY6Uzm9JGkEieQavjao67x9ahupY3h7tx0etgRwe1YwkV11HQ=
